apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-to-appservice
spec:
  template:
    spec:
      containers:
      - name: azure-cli
        image: mcr.microsoft.com/azure-cli
        command:
        - /bin/sh
        - -c
        - |
          az login --service-principal \
            --username b52c23ca-f0ed-4c59-9a40-f788a44c3b2d \
            --password $AZURE_CLIENT_SECRET \
            --tenant 7492deb3-56cf-4f2f-a137-debd02585176

          az webapp config container set \
            --name myapp-service \
            --resource-group my-rg \
            --docker-custom-image-name myregistry.azurecr.io/myapp:latest \
            --docker-registry-server-url https://myregistry.azurecr.io
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: clientId
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: clientSecret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: tenantId
      restartPolicy: Never
