apiVersion: batch/v1
kind: Job

metadata:
  generateName: deploy-to-appservice-
  namespace: argo-appservice-test
  labels:
    app: deploy-to-appservice
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  template:
    metadata:
      labels:
        app: deploy-to-appservice
    spec:
      containers:
        - name: azure-cli
          image: mcr.microsoft.com/azure-cli
          env:
            # Creds from Secret
            - name: AZURE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appservice-secret
                  key: AZURE_USERNAME
            - name: AZURE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appservice-secret
                  key: AZURE_PASSWORD
            - name: AZURE_TENANT
              valueFrom:
                secretKeyRef:
                  name: appservice-secret
                  key: AZURE_TENANT
            # app-service configs from ConfigMap
            - name: WEBAPP_NAME
              valueFrom:
                configMapKeyRef:
                  name: appservice-config
                  key: WEBAPP_NAME
            - name: RESOURCE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: appservice-config
                  key: RESOURCE_GROUP
            - name: DOCKER_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: appservice-config
                  key: DOCKER_IMAGE_NAME
            - name: DOCKER_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: appservice-config
                  key: DOCKER_REGISTRY_URL
          command:
            - /bin/sh
            - '-c'
            - |
              echo "Starting Azure CLI job at $(date)"
              
              az login --service-principal \
                --username $AZURE_USERNAME \
                --password $AZURE_PASSWORD \
                --tenant $AZURE_TENANT

              az webapp config container set \
                --name $WEBAPP_NAME \
                --resource-group $RESOURCE_GROUP \
                --docker-custom-image-name $DOCKER_IMAGE_NAME \
                --docker-registry-server-url $DOCKER_REGISTRY_URL
                
              echo "Azure CLI job completed at $(date)"

      restartPolicy: Never
      imagePullSecrets:
        - name: dockerhub-secret

  backoffLimit: 0
  ttlSecondsAfterFinished: 300