apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-to-appservice  # Use a fixed name for the Job
  namespace: argo-appservice-test
  labels:
    app: deploy-to-appservice
  annotations:
    argocd.argoproj.io/hook: Sync  # Treat this Job as a sync hook
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  # Delete the Job after it succeeds
    argocd.argoproj.io/sync-wave: "1"  # Run in a specific sync wave

spec:
  selector:
    matchLabels:
      app: deploy-to-appservice  # Selector must match the labels in the template
  template:
    metadata:
      labels:
        app: deploy-to-appservice  # Labels must match the selector
    spec:
      containers:
        - name: azure-cli
          image: mcr.microsoft.com/azure-cli
          command:
            - /bin/sh
            - '-c'
            - |
              az login --service-principal \
                --username 1a649b3f-1eb8-40aa-8574-a7dfc1f1becb \
                --password Mr48Q~63w5uzaG5X3MM6FmZasfR6MgmS.k-3zcHC \
                --tenant 7492deb3-56cf-4f2f-a137-debd02585176

              az webapp config container set \
                --name argo-appservice-test \
                --resource-group argo-appservice-test \
                --docker-custom-image-name busybox \
                --docker-registry-server-url https://index.docker.io
      restartPolicy: Never
      activeDeadlineSeconds: 300  # Limit Job runtime to 5 minutes
  backoffLimit: 0  # Disable retries to prevent multiple pods
  ttlSecondsAfterFinished: 300  # Clean up Job 5 minutes after completion