apiVersion: v1
kind: ConfigMap
metadata:
  name: appservice-config
  namespace: argo-appservice-test
data:
  WEBAPP_NAME: argo-appservice-test
  RESOURCE_GROUP: argo-appservice-test
  DOCKER_IMAGE_NAME: tsailendranath/alpine:dev-8824748d4d24159ed36eb502a0664029c9efbbad
  DOCKER_REGISTRY_URL: https://index.docker.io
