apiVersion: v1
kind: Secret
metadata:
  name: appservice-secret
  namespace: argo-appservice-test
type: Opaque
data:
  AZURE_USERNAME: MWE2NDliM2YtMWViOC00MGFhLTg1NzQtYTdkZmMxZjFiZWNi
  AZURE_PASSWORD: TXI0OFF+NjN3NXV6YUc1WDNNTTZGbVphc2ZSNk1nbVMuay0zemNIQw==
  AZURE_TENANT: NzQ5MmRlYjMtNTZjZi00ZjJmLWExMzctZGViZDAyNTg1MTc2