name: Build, Push Docker Image & Update ConfigMap

on:
  push:
    branches:
      - main 
env:
  DOCKERHUB_USERNAME: tsailendranath
  DOCKERHUB_TOKEN: Sn@7325912909

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set Commit SHA
        id: vars
        run: echo "sha_tag=dev-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }}

  # update-configmap:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup kubectl
  #       uses: azure/setup-kubectl@v3

  #     - name: Load Kubeconfig
  #       run: |
  #         mkdir -p $HOME/.kube
  #         echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

  #     - name: Update ConfigMap with new image tag
  #       run: |
  #         kubectl get configmap my-configmap -n my-namespace -o yaml > configmap.yaml
  #         sed -i "s/IMAGE_TAG:.*/IMAGE_TAG: \"${{ needs.build-and-push.outputs.sha_tag }}\"/" configmap.yaml
  #         kubectl apply -f configmap.yaml
