name: Build, Push Docker Image & Update ConfigMap

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Generate Unique Tag
        id: vars
        run: |
          COMMIT_HASH=${{ github.sha }}
          echo "sha_tag=dev-${COMMIT_HASH}" >> $GITHUB_OUTPUT


      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }}

      - name: Update DOCKER_IMAGE_NAME in configmap
        run: |
          CONFIGMAP_FILE="./configmap.yaml"
          NEW_TAG="${{ secrets.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }}"

          # Safely update the DOCKER_IMAGE_NAME in the ConfigMap
          sed -i "s|^\( *DOCKER_IMAGE_NAME:\).*|\1 ${NEW_TAG}|" $CONFIGMAP_FILE

      - name: Debug - Show Updated ConfigMap
        run: cat ./configmap.yaml

      - name: Commit & Push Changes If Necessary
        run: |
          git config --global user.email "sailendranath.thakur@ecanarys.com"
          git config --global user.name "Sailendranath Thakur"

          # Check if there are changes to commit
          if ! git diff --quiet; then
            git add ./configmap.yaml
            git commit -m "[skip ci] updated image tag to alpine:${{ steps.vars.outputs.sha_tag }}"
            git push
          else
            echo "No changes to commit."
            echo "No changes to commit."
          fi
