name: Build, Push Docker Image & Update ConfigMap

on:
  push:
    branches:
      - main 

permissions:
  contents: write

env:
  DOCKERHUB_USERNAME: tsailendranath
  DOCKERHUB_TOKEN: Sn@7325912909

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set Commit SHA
        id: vars
        run: echo "sha_tag=dev-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/alpine:${{ steps.vars.outputs.sha_tag }}

      - name: Update DOCKER_IMAGE_NAME in configmap
        run: |
          CONFIGMAP_FILE="./configmap.yaml"

          # Update the DOCKER_IMAGE_NAME value
          sed -i "s|DOCKER_IMAGE_NAME:.*|DOCKER_IMAGE_NAME: tsailendranath/alpine:${{ steps.vars.outputs.tag }}|" $CONFIGMAP_FILE

      - name: Commit & Push changes
        run: |
          git config --global user.email "sailendranath.thakur@ecanarys.com"
          git config --global user.name "Sailendranath Thakur"
          git commit -am "chore: update image tag to alpine:${{ steps.vars.outputs.tag }}"
          git push

 